name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdown-yaml-lint:
    name: Markdown and YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: ".*\\.code-workspace$"